language: python
python: 
- "3.8"
install:
- pip3 install numpy
- pip3 install yaml
- pip3 install times
- pip3 install datetime
script: 
- pytest # run tests
after_success:
- codecov # submit coverage
